# -*- coding: utf-8 -*-
"""deshboard 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJAUoMRS9cMhkeOfRuMjYg2hTwAb1lqd
"""

# Biblioteca necessárias

!pip install streamlit pandas pyngrok -q

from google.colab import userdata
from pyngrok import ngrok # Changed 'import ngrok' to 'from pyngrok import ngrok'

# Get the ngrok authentication token from Colab Secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

# Authenticate ngrok
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

print('ngrok authenticated successfully!')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# import streamlit as st
# 
# st.set_page_config(page_title="Dashboard de Movimentação", layout="wide")
# 
# st.title("📊 Dashboard de Movimentações")
# 
# 
# @st.cache_data
# def load_data(sheet_id):
#     url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
#     df = pd.read_csv(url)
# 
#     # Renomeia as colunas do pandas para garantir que fiquem padronizadas
#     df.columns = [
#         "Matricula",
#         "Nome",
#         "Posto/Grad",
#         "Atividade",
#         "OME",
#         "Data_de_moviment",
#         "Municipio",
#         "Região",
#         "OME_Anterior",
#         "SEXO",
#         "NÚMERO_DE_CONTATO",
#          # Ajuste o nome da 11ª coluna caso seja diferente
#     ]
#     return df
# 
# 
# SHEET_ID = "1XSa9NOQVuaWv1_CIVndoZf1aW2pJJmoY"
# 
# try:
#     df = load_data(SHEET_ID)
# 
#     # --- BARRA LATERAL / FILTROS ---
#     st.sidebar.header("🔍 Filtros")
# 
#     # Filtro por Posto/Grad
#     posto_opt = ["Todos"] + list(df["Posto/Grad"].dropna().unique())
#     posto_sel = st.sidebar.selectbox("Posto/Grad:", posto_opt)
# 
#     # Filtro por Município
#     muni_opt = ["Todos"] + list(df["Municipio"].dropna().unique())
#     muni_sel = st.sidebar.selectbox("Município:", muni_opt)
# 
#     # Filtro por Região
#     reg_opt = ["Todos"] + list(df["Região"].dropna().unique())
#     reg_sel = st.sidebar.selectbox("Região:", reg_opt)
# 
#     # Aplicando os Filtros aos Dados
#     df_filtrado = df.copy()
# 
#     if posto_sel != "Todos":
#         df_filtrado = df_filtrado[df_filtrado["Posto/Grad"] == posto_sel]
# 
#     if muni_sel != "Todos":
#         df_filtrado = df_filtrado[df_filtrado["Municipio"] == muni_sel]
# 
#     if reg_sel != "Todos":
#         df_filtrado = df_filtrado[df_filtrado["Região"] == reg_sel]
# 
#     # --- EXIBIÇÃO DE MÉTRICAS ---
#     m1, m2, m3 = st.columns(3)
#     m1.metric("Total Registrados", len(df_filtrado))
#     m2.metric("Municípios Filtrados", df_filtrado["Municipio"].nunique())
#     m3.metric("Postos/Graduações", df_filtrado["Posto/Grad"].nunique())
# 
#     st.markdown("---")
# 
#     # --- TABELA DE DADOS ---
#     st.subheader("📋 Registros Encontrados")
#     st.dataframe(df_filtrado, use_container_width=True)
# 
#     # --- GRÁFICO POR POSTO/GRAD ---
#     st.subheader("📈 Distribuição por Posto/Graduação")
#     st.bar_chart(df_filtrado["Posto/Grad"].value_counts())
# 
# except Exception as e:
#     st.error(f"Erro ao carregar ou processar os dados: {e}")

# Passo 3: Iniciar o Dashboard

import urllib

# Exibe a senha de IP do Colab
ip = (
    urllib.request.urlopen("https://ipv4.icanhazip.com")
    .read()
    .decode("utf8")
    .strip()
)
print(f"🔑 SUA SENHA DE ACESSO (IP Público): {ip}\n")

# Inicia o Streamlit + LocalTunnel
!streamlit run app.py &>/content/logs.txt &
!npx localtunnel --port 8501

# Instalar as dependências

!pip install -q streamlit pandas pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# import streamlit as st
# 
# st.set_page_config(page_title="Dashboard de Movimentação", layout="wide")
# 
# # --- ADICIONANDO IMAGEM NO TOPO ---
# # Substitua a URL abaixo pela URL da sua logo ou banner
# URL_LOGO = "https://share.google/NNdZkH4CnCtQUHluq"
# 
# col_logo, col_titulo = st.columns([1, 4])
# with col_logo:
#     st.image(URL_LOGO, width=120)
# with col_titulo:
#     st.title("📊 Dashboard de Movimentações")
# 
# 
# @st.cache_data(ttl=5)
# def load_data(sheet_id):
#     url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"
#     df = pd.read_csv(url)
#     df.columns = [str(col).strip() for col in df.columns]
#     return df
# 
# 
# SHEET_ID = "1XSa9NOQVuaWv1_CIVndoZf1aW2pJJmoY"
# 
# try:
#     # --- LOGO NA BARRA LATERAL ---
#     st.sidebar.image(URL_LOGO, use_container_width=True)
# 
#     if st.sidebar.button("🔄 Forçar Atualização"):
#         st.cache_data.clear()
#         st.rerun()
# 
#     df = load_data(SHEET_ID)
# 
#     # --- BUSCA DIGITADA ---
#     termo_busca = st.text_input("🔍 Digite algo para pesquisar na planilha:", "")
#     df_filtrado = df.copy()
# 
#     if termo_busca:
#         mascara = df_filtrado.astype(str).apply(
#             lambda col: col.str.contains(termo_busca, case=False, na=False)
#         )
#         df_filtrado = df_filtrado[mascara.any(axis=1)]
# 
#     # --- FILTROS LATERAIS ---
#     st.sidebar.header("🎛️ Filtros por Coluna")
#     for coluna in df.columns:
#         valores_unicos = (
#             df[coluna].dropna().astype(str).unique().tolist()
#         )
#         valores_unicos.sort()
#         opcoes = ["Todos"] + valores_unicos
#         escolha = st.sidebar.selectbox(f"{coluna}:", opcoes, key=coluna)
# 
#         if escolha != "Todos":
#             df_filtrado = df_filtrado[
#                 df_filtrado[coluna].astype(str) == escolha
#             ]
# 
#     # --- MÉTRICAS ---
#     m1, m2, m3 = st.columns(3)
#     m1.metric("Registros Filtrados", len(df_filtrado))
#     m2.metric("Total de Registros", len(df))
#     m3.metric(
#         "% Exibido",
#         f"{(len(df_filtrado) / len(df)) * 100:.1f}%" if len(df) > 0 else "0%",
#     )
# 
#     st.markdown("---")
# 
#     # --- TABELA DE DADOS ---
#     st.subheader("📋 Registros Encontrados")
#     st.dataframe(df_filtrado, use_container_width=True)
# 
#     # --- GRÁFICO AUTOMÁTICO ---
#     st.subheader("📈 Análise Visual")
#     coluna_grafico = st.selectbox(
#         "Escolha a coluna para o gráfico:", list(df.columns)
#     )
#     if len(df_filtrado) > 0:
#         st.bar_chart(df_filtrado[coluna_grafico].value_counts())
# 
# except Exception as e:
#     st.error(f"Erro ao carregar os dados: {e}")

import time

!pkill -f streamlit
!pkill -f cloudflared

!streamlit run app.py --server.port 8501 --server.address 127.0.0.1 &>/content/logs.txt &

time.sleep(3)

!./cloudflared tunnel --url http://127.0.0.1:8501
